### ISSUE TITLE
Question - How to automate copy_xlsx_styles for multiple sheets

### ISSUE THREAD

**Issue by SSMK-wq** [Sydney-Informatics-Hub/copy_xlsx_styles#1]
I have a master excel sheet (with single sheet in it) with certain formatting such as color, freeze panes etc

Now, I would like to copy that format to `child sheet` (which has multiple individual work sheets in it).

How can I install and import this python package?

**Comment by SSMK-wq** [comment]
@jnothman - I tried running the below command

![image](https://user-images.githubusercontent.com/30723825/155886242-ce620859-ad72-4191-b740-f446781517ce.png)

when I do the above, I see that nothing happens. (command is executed successfully though. no error)

I have my format in the `style_sheet.xlsx`, data in the `data_sheet.xlsx` and I want the output to be stored in the `test.xlsx`.

However, when I execute the command in `command prompt`, I see that my `copy-styles.py` file (opens up in notepad) but nothing happens after that. How can I copy the format? Help please

I also tried with full path as shown below

`C:\Users\test\Desktop\copy-styles.py [-h] C:\Users\test\Desktop\style_sheet.xlsx C:\Users\test\Desktop\data_sheet.xlsx C:\Users\test\Desktop\test.xlsx`

It opens in notepad because I copied the `copy_xlsx_style.py` content and pasted in a text file and saved it as `.py` file named as `copy-styles.py`.

Can I check how can we do this correctly? Your help is appreciated

**Comment by jnothman** [comment]
It sounds like you might be more familiar doing it from within Python than from the command-line. Can I suggest you:
* put `copy_xlsx_styles.py` in the working directory where you will code
* use `openpyxl` to open the sheets you want to copy from and to. Assign those worksheets to variable names like `style_sheet` and `data_sheet`
* Then you can use `from copy_xlsx_styles import copy_styles` and `copy_styles(style_sheet, data_sheet)`. Finally, save the open workbook.

**Comment by SSMK-wq** [comment]
@jnothman - Unfortunately, I encountered the below error

```
AttributeError                            Traceback (most recent call last)
C:\Users\test\AppData\Local\Temp/ipykernel_22940/543609893.py in <module>
----> 1 copy_styles(style_sheet, data_sheet)

~\Downloads\copy_xlsx_styles.py in copy_styles(style_sheet, data_sheet)
     39 
     40 def copy_styles(style_sheet, data_sheet):
---> 41     max_matched_row = min(style_sheet.max_row, data_sheet.max_row)
     42     max_matched_col = min(style_sheet.max_column, data_sheet.max_column)
     43 

AttributeError: 'list' object has no attribute 'max_row'
```

You can find my python code below

```
import pandas as pd
import numpy as np
import openpyxl
from openpyxl import load_workbook
from copy_xlsx_styles import copy_styles

wb = load_workbook(filename = 'style_sheet.xlsx')
wb1 = load_workbook(filename = 'data_sheet.xlsx')
style_sheet = wb.sheetnames #there is only one sheet
data_sheet = wb1.sheetnames @there is only one sheet
copy_styles(style_sheet, data_sheet)
```

If I use the below in snippet in my code, I get a different error (shown below)

```
style_sheet = wb.sheetnames[0]
data_sheet = wb1.sheetnames[0]
```

`AttributeError: 'str' object has no attribute 'max_row'`

Even if I modify my code like below

```
style_sheet = load_workbook(filename = 'sty1.xlsx')
data_sheet = load_workbook(filename = 'dat1.xlsx')
```

I still get the same error

`AttributeError: 'Workbook' object has no attribute 'max_row'`


@jnothman  - help me please

files can be downloaded from here

[sty1.xlsx](https://github.com/Sydney-Informatics-Hub/copy_xlsx_styles/files/8162286/sty1.xlsx)
[dat1.xlsx](https://github.com/Sydney-Informatics-Hub/copy_xlsx_styles/files/8162293/dat1.xlsx)

**Comment by jnothman** [comment]
```
style_sheet = wb.sheetnames
```
should be
```
style_sheet = wb.worksheets[0]
````

**Comment by SSMK-wq** [comment]
@jnothman - Unfortunately, I ran into another error

When I do the below,

```
style_sheet = wb.worksheets[0]
data_sheet = wb1.worksheets[0]
copy_styles(style_sheet, data_sheet)
```

I got the below error

```
ValueError                                Traceback (most recent call last)
C:\Users\test\AppData\Local\Temp/ipykernel_10876/543609893.py in <module>
----> 1 copy_styles(style_sheet, data_sheet)

~\Downloads\copy_xlsx_styles.py in copy_styles(style_sheet, data_sheet)
     66                     yield style_cell, data_cell
     67 
---> 68     for style_cell, data_cell in generate_cell_pairs():
     69         if style_cell.has_style:
     70             for attr in CELL_ATTRS:

~\Downloads\copy_xlsx_styles.py in generate_cell_pairs()
     61         if data_sheet.max_row > style_sheet.max_row and data_sheet.max_column > style_sheet.max_column:
     62             style_row, = style_sheet.iter_rows(min_row=max_matched_row, max_col=max_matched_col)
---> 63             style_cell, = style_row
     64             for data_row in data_sheet.iter_rows(min_row=max_matched_row + 1, min_col=max_matched_col + 1):
     65                 for data_cell in data_row:

ValueError: too many values to unpack (expected 1)
```

If you want further info, I am mainly trying to do something like below

I am counting on your package to do the below (copy format of one sheet (from style_sheet) to multiple sheets (date_sheet).

```
for sheet_from, sheet_to in product(wb.worksheets, wb1.worksheets):
    print(sheet_from)
    print(sheet_to)
    copy_styles(sheet_from, sheet_to)

```
help me please

**Comment by jnothman** [comment]
I've updated the failing line in the script - it was not tested on data where the style sheet has more columns than the data sheet.

**Comment by SSMK-wq** [comment]
@jnothman - but the sample files that I shared has same number of columns in both style and data sheet. 

Is it because the data sheet looks like this (where there is dark border, so the code is considering it as another column)?

![image](https://user-images.githubusercontent.com/30723825/156280159-7f3e2b9b-8075-4400-ba84-fc6dce300734.png)

My style sheet too has only 4 columns

![image](https://user-images.githubusercontent.com/30723825/156280256-888f7d58-63f4-457b-b54e-cc723ed6553a.png)


Anyway, will try the updated code

**Comment by SSMK-wq** [comment]
@jnothman - same error again on the same line (but with updated code)

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Users\test\AppData\Local\Temp/ipykernel_10876/1025864706.py in <module>
      2     print(sheet_from)
      3     print(sheet_to)
----> 4     copy_styles(sheet_from, sheet_to)

~\Downloads\copy_xlsx_styles.py in copy_styles(style_sheet, data_sheet)
     66                     yield style_cell, data_cell
     67 
---> 68     for style_cell, data_cell in generate_cell_pairs():
     69         if style_cell.has_style:
     70             for attr in CELL_ATTRS:

~\Downloads\copy_xlsx_styles.py in generate_cell_pairs()
     61         if data_sheet.max_row > style_sheet.max_row and data_sheet.max_column > style_sheet.max_column:
     62             style_row, = style_sheet.iter_rows(min_row=max_matched_row, max_col=max_matched_col)
---> 63             style_cell = next(iter(style_row))
     64             for data_row in data_sheet.iter_rows(min_row=max_matched_row + 1, min_col=max_matched_col + 1):
     65                 for data_cell in data_row:

ValueError: too many values to unpack (expected 1)
```

**Comment by jnothman** [comment]
No, that's showing me that you need to reload the copy_xlsx_styles module in your Python interpreter.

**Comment by SSMK-wq** [comment]
@jnothman - code works now. But may be am making a mistake somewhere. I don't see any format being copied to my data sheet. When I reopen `dat.xlsx`, I see that there is no format applied (from style sheet). Am really sorry if I am making a blunder.

what could be the reason? Should I give any output argument?

When I tried something like below

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\test\AppData\Local\Temp/ipykernel_10876/878097635.py in <module>
      2     print(sheet_from)
      3     print(sheet_to)
----> 4     copy_styles(sheet_from, sheet_to,'out.xlsx')

TypeError: copy_styles() takes 2 positional arguments but 3 were given
```


![image](https://user-images.githubusercontent.com/30723825/156281317-7c45f58e-2b05-49b7-94d3-fcf55ff1f99a.png)

**Comment by jnothman** [comment]
It doesn't save. Use `data_sheet.parent.save('out.xlsx')`

**Comment by SSMK-wq** [comment]
@jnothman - for some reason, there is a slight mistmatch in the output. Can help me on how can I fix this mismatch in format across sheets? would really be grateful

ex: Sheet1 has 2 rows of yellow color (but style sheet has only 1 row of yellow color)

![image](https://user-images.githubusercontent.com/30723825/156282165-4eefac21-eb91-46c4-a163-7c0876fe4da5.png)

whereas Sheet 2 has correct formatting - only 1 row of yellow color (same as style sheet)

![image](https://user-images.githubusercontent.com/30723825/156282262-67a1e5e1-67ad-4dc2-aad0-4f2d7be0a054.png)

This is the code that I tried below

```
for sheet_from, sheet_to in product(wb.worksheets, wb1.worksheets):
    print(sheet_from)
    print(sheet_to)
    copy_styles(sheet_from, sheet_to)
    sheet_to.parent.save('out.xlsx')
```

**Comment by SSMK-wq** [comment]
@jnothman - Do you know why is this 1st sheet alone has 2 yellow color lines whereas 2nd sheet has correct number of lines?

When I looked at your code below, currently my file has data_rows < style_rows but columns are same in both files.

Additionally, another issue that I encountered was color for one of the cell was different between style and output_xlsx sheet

My ID column in style sheet has a color like below

![image](https://user-images.githubusercontent.com/30723825/156291299-ff9073f7-5e8d-490f-88ba-f760bad7bd60.png)

but ID color in output sheet is different (shown below)

![image](https://user-images.githubusercontent.com/30723825/156291355-4d3cd52b-895c-4e54-a622-6ffd9e1f541f.png)

May I kindly seek your help to fix this? Or can you guide me on where to look in your code to get the color attribute and reason for 2 lines of yellow color?

I was going through the below but wasn't able to see a condition where data_rows < style_rows.

Sorry, am not a software developer, so, trying to make sense just by looking at it. But yes, your tool is really helpful. It can help me save time from my manual tasks. Hence, am excited to see it working but for some reason (due to my limitations), I am not able to get the exact ouptut


```
  if data_sheet.max_column > style_sheet.max_column:
            for style_row, data_row in zip(style_sheet.iter_rows(max_row=max_matched_row, min_col=max_matched_col, max_col=max_matched_col),
                                           data_sheet.iter_rows(max_row=max_matched_row, min_col=max_matched_col + 1)):
                style_cell, = style_row
                for data_cell in data_row:
                    yield style_cell, data_cell

        if data_sheet.max_row > style_sheet.max_row:
            style_row, = style_sheet.iter_rows(min_row=max_matched_row, max_col=max_matched_col)
            for data_row in data_sheet.iter_rows(min_row=max_matched_row + 1, max_col=max_matched_col):
                yield from zip(style_row, data_row)

        if data_sheet.max_row > style_sheet.max_row and data_sheet.max_column > style_sheet.max_column:
            style_row, = style_sheet.iter_rows(min_row=max_matched_row, max_col=max_matched_col)
            style_cell = next(iter(style_row))
            for data_row in data_sheet.iter_rows(min_row=max_matched_row + 1, min_col=max_matched_col + 1):
                for data_cell in data_row:
                    yield style_cell, data_cell
```

**Comment by SSMK-wq** [comment]
@jnothman - Okay, I think I found out why it happens. not sure whether this helps. but I don't know why excel behaves that way. now, the only outstanding issue is the color difference.

When I press CTRL+A in sheet1 of data sheet, it looks like below (which lead to two rows of yellow color)

![image](https://user-images.githubusercontent.com/30723825/156297137-36bb3a94-187a-4bec-87c9-c486a26f8b21.png)


whereas when I press  CTRL+A in sheet2 of data sheet, it looks like below (which is correct and shows only one line)

![image](https://user-images.githubusercontent.com/30723825/156297093-10cd0d18-ad8e-4860-b9f0-99198e2eb111.png)

**Comment by jnothman** [comment]
Great sleuthing! Yes, maybe we shouldn't rely on what openpyxl says is the last row, but check for any non-empty cells???

**Comment by jnothman** [comment]
> I was going through the below but wasn't able to see a condition where data_rows < style_rows.

The idea of `max_matched_row` and `max_matched_col` deals with the columns up to and including the last that they have in common. Where there are additional style rows, what do you expect should happen?

> Sorry, am not a software developer, so, trying to make sense just by looking at it. 

I'm impressed at what you've managed so far. Time for a career change? :D

It'd be hard to work out why you're getting a different ID header colour without looking closer at your specific spreadsheets (which I'll admit I don't have time for). You'll see that colour is [copied](https://github.com/Sydney-Informatics-Hub/copy_xlsx_styles/blob/5ca7d3f418716a960c8bc5f3a228c86b9b5b4a2b/copy_xlsx_styles.py#L71) as the `fill` component of [`CELL_ATTRS`](https://github.com/Sydney-Informatics-Hub/copy_xlsx_styles/blob/5ca7d3f418716a960c8bc5f3a228c86b9b5b4a2b/copy_xlsx_styles.py#L21)

**Comment by SSMK-wq** [comment]
No worries, I understand. Hopefully my biz accepts the color difference as minor (and hope I will not be asked to change all this manually)..haha. Nonetheless, very useful tool. Appreciate your help
