### ISSUE TITLE
Dynamic fields copied as party of style transfer?

### ISSUE THREAD

**Issue by SSMK-wq** [Sydney-Informatics-Hub/copy_xlsx_styles#3]
I have couple of excel fields like below

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/test~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/test~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

700 | 350
-- | --
Current Amount | New Amount
100 | 50
100 | 50
100 | 50
100 | 50
100 | 50
100 | 50
100 | 50

</body>

</html>

As you can see that both the fields are dynamic. Meaning, when I change any of the values in the column, their corresponding total would change. You can see below based on change of value for 1st row (for both columns), the total is reduced

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/test~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/test~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

600 | 300
-- | --
Current Amount | New Amount
0 | 0
100 | 50
100 | 50
100 | 50
100 | 50
100 | 50
100 | 50

</body>

</html>

So, does `copy_styles` take care of this as well?

In the code below, I don't see `formula`. So, does it mean it is not handled in copy_styles?

```
UNSUPPORTED_ATTRS = {'style', 'customFormat', 's', 'customHeight', 'customWidth'}
CELL_ATTRS = list({'font', 'fill', 'border', 'number_format', 'protection', 'alignment', 'style'} - UNSUPPORTED_ATTRS)
ROW_ATTRS = CELL_ATTRS + list(set(RowDimension.__fields__) - UNSUPPORTED_ATTRS)
COL_ATTRS = CELL_ATTRS + list(set(ColumnDimension.__fields__) - UNSUPPORTED_ATTRS)
```

**Comment by jnothman** [comment]
No, currently only style is copied. Copying formulas would need some speccing out. For example, do you expect that there will be nothing in the corresponding cell on the data sheet, and then the formula will just be copied across unchanged? Or is the cell to be inserted? The formula modified?

**Comment by SSMK-wq** [comment]
I think formula should just be copied across unchanged. But I understand that `formula` is a tricky part as there are multiple ways how users expect formula to be used. So, now that I think I understand it is challenging and requires more time.
