### ISSUE TITLE
CSV support for copy_styles

### ISSUE THREAD

**Issue by SSMK-wq** [Sydney-Informatics-Hub/copy_xlsx_styles#4]
I see that currently the code only takes the .xlsx files as input.

But the style, font, formula can also be used across .csv files.

Is there any plans to offer support for csv in future? or do you think not many people use CSV for this type of stuff and you don't see providing any support for csv?

**Comment by jnothman** [comment]
A big part of the intention here is to support users generating data and then styling it according to some template spreadsheet. So absolutely, it makes sense to support CSV, and it would not be a big change assuming defaults from [pandas.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) are acceptable.
