### ISSUE TITLE
Linking two sheets for formatting

### ISSUE THREAD

**Issue by SSMK-wq** [Sydney-Informatics-Hub/copy_xlsx_styles#5]
Hi,

Sorry to be back again asking you questions.

Currently, I have a problem where my excel file has 2 sheets. Let's consider sheet1 and sheet2

Each sheet has different format. But the challenge is when I enter values in sheet1, there is some formula beneath it which automatically makes some output populate in sheet2

For ex: If I enter `Gender = M` in sheet1, there is an automatic entry in sheet2 - which is Male.

This is just a dummy example. but hope this helps you understand what I am trying to say.

When I use copy_styles_xlsx, does it take care of this?

Sorry, if I am asking expecting sky to come down using a python script..or even if its too much...lol..

Can share your views on how can it be done?

**Comment by jnothman** [comment]
There's plenty a Python script _can_ do, but this script is currently limited to styling.

**Comment by jnothman** [comment]
However, you can still use standard excel formulas to work with values from other sheets.
